["default"]
15_min = 8
hourly = 24
daily = 0
monthly = 0

# root_pool
["root_pool/home"]
15_min = 8
hourly = 24
daily = 14
monthly = 0

["root_pool/root"]
15_min = 8
hourly = 24
daily = 0
monthly = 0

["root_pool/nix"]
15_min = 4
hourly = 0
daily = 0
monthly = 0

["root_pool/var"]
15_min = 8
hourly = 24
daily = 30
monthly = 6
# storage
["storage/ollama"]
15_min = 2
hourly = 0
daily = 0
monthly = 0

["storage/secure"]
15_min = 0
hourly = 0
daily = 0
monthly = 0

["storage/secure/plex"]
15_min = 6
hourly = 2
daily = 1
monthly = 0

["storage/secure/transmission"]
15_min = 4
hourly = 0
daily = 0
monthly = 0

["storage/secure/secrets"]
15_min = 8
hourly = 24
daily = 30
monthly = 12

# media
["media/temp"]
15_min = 2
hourly = 0
daily = 0
monthly = 0

["media/secure"]
15_min = 0
hourly = 0
daily = 0
monthly = 0

["media/secure/plex"]
15_min = 6
hourly = 2
daily = 1
monthly = 0

["media/secure/share"]
15_min = 4
hourly = 0
daily = 0
monthly = 0

["media/secure/github-runners"]
15_min = 6
hourly = 2
daily = 1
monthly = 0

["media/secure/notes"]
15_min = 8
hourly = 24
daily = 30
monthly = 12

["media/secure/docker"]
15_min = 3
hourly = 12
daily = 14
monthly = 2

# scratch
["scratch/transmission"]
15_min = 2
hourly = 0
daily = 0
monthly = 0
