"""created contact api.

Revision ID: edd7dd61a3d2
Revises:
Create Date: 2026-01-11 15:45:59.909266

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

from python.orm import RichieBase

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "edd7dd61a3d2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

schema = RichieBase.schema_name


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("current_job", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("goals", sa.String(), nullable=True),
        sa.Column("legal_name", sa.String(), nullable=True),
        sa.Column("profile_pic", sa.String(), nullable=True),
        sa.Column("safe_conversation_starters", sa.String(), nullable=True),
        sa.Column("self_sufficiency_score", sa.Integer(), nullable=True),
        sa.Column("social_structure_style", sa.String(), nullable=True),
        sa.Column("ssn", sa.String(), nullable=True),
        sa.Column("suffix", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("topics_to_avoid", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
        schema=schema,
    )
    op.create_table(
        "need",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_need")),
        schema=schema,
    )
    op.create_table(
        "contact_need",
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("need_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            [f"{schema}.contact.id"],
            name=op.f("fk_contact_need_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["need_id"], [f"{schema}.need.id"], name=op.f("fk_contact_need_need_id_need"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("contact_id", "need_id", name=op.f("pk_contact_need")),
        schema=schema,
    )
    op.create_table(
        "contact_relationship",
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("related_contact_id", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.Column("closeness_weight", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            [f"{schema}.contact.id"],
            name=op.f("fk_contact_relationship_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["related_contact_id"],
            [f"{schema}.contact.id"],
            name=op.f("fk_contact_relationship_related_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("contact_id", "related_contact_id", name=op.f("pk_contact_relationship")),
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact_relationship", schema=schema)
    op.drop_table("contact_need", schema=schema)
    op.drop_table("need", schema=schema)
    op.drop_table("contact", schema=schema)
    # ### end Alembic commands ###
