"""removed ds table from richie DB.

Revision ID: c8a794340928
Revises: 6b275323f435
Create Date: 2026-03-29 15:29:23.643146

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from python.orm import RichieBase

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c8a794340928"
down_revision: str | None = "6b275323f435"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

schema = RichieBase.schema_name


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vote_record", schema=schema)
    op.drop_index(op.f("ix_vote_congress_chamber"), table_name="vote", schema=schema)
    op.drop_index(op.f("ix_vote_date"), table_name="vote", schema=schema)
    op.drop_index(op.f("ix_legislator_bioguide_id"), table_name="legislator", schema=schema)
    op.drop_table("legislator", schema=schema)
    op.drop_table("vote", schema=schema)
    op.drop_index(op.f("ix_bill_congress"), table_name="bill", schema=schema)
    op.drop_table("bill", schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vote",
        sa.Column("congress", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chamber", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("session", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("vote_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("question", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("result", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("result_text", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("vote_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("yea_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("nay_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("not_voting_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("present_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("bill_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bill_id"], [f"{schema}.bill.id"], name=op.f("fk_vote_bill_id_bill")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vote")),
        sa.UniqueConstraint(
            "congress",
            "chamber",
            "session",
            "number",
            name=op.f("uq_vote_congress_chamber_session_number"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        schema=schema,
    )
    op.create_index(op.f("ix_vote_date"), "vote", ["vote_date"], unique=False, schema=schema)
    op.create_index(op.f("ix_vote_congress_chamber"), "vote", ["congress", "chamber"], unique=False, schema=schema)
    op.create_table(
        "vote_record",
        sa.Column("vote_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("legislator_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("position", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            [f"{schema}.legislator.id"],
            name=op.f("fk_vote_record_legislator_id_legislator"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vote_id"], [f"{schema}.vote.id"], name=op.f("fk_vote_record_vote_id_vote"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("vote_id", "legislator_id", name=op.f("pk_vote_record")),
        schema=schema,
    )
    op.create_table(
        "legislator",
        sa.Column("bioguide_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("thomas_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("lis_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("govtrack_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("opensecrets_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("fec_ids", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("official_full_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("nickname", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("gender", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("current_party", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("current_state", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("current_district", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("current_chamber", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legislator")),
        schema=schema,
    )
    op.create_index(op.f("ix_legislator_bioguide_id"), "legislator", ["bioguide_id"], unique=True, schema=schema)
    op.create_table(
        "bill",
        sa.Column("congress", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("bill_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("title_short", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("official_title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("status_at", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("sponsor_bioguide_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("subjects_top_term", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill")),
        sa.UniqueConstraint(
            "congress",
            "bill_type",
            "number",
            name=op.f("uq_bill_congress_type_number"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        schema=schema,
    )
    op.create_index(op.f("ix_bill_congress"), "bill", ["congress"], unique=False, schema=schema)
    # ### end Alembic commands ###
