{
 "title": "Process Live PID",
 "tags": [
  "monitoring",
  "process"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Top PID CPU",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20, rate(namedprocess_namegroup_cpu_seconds_total[2m]))",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "Top PID RSS",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, namedprocess_namegroup_memory_bytes{memtype=\"resident\"})",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "Top PID Read I/O",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(20, rate(namedprocess_namegroup_read_bytes_total[2m]))",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "Top PID Write I/O",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(20, rate(namedprocess_namegroup_write_bytes_total[2m]))",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  }
 ]
}