zpool = ["root_pool", "storage", "torrenting", "media"]
services = [
    "audiobookshelf",
    "docker-cloud_flare_tunnel",
    "haproxy",
    "docker-qbit",
    "docker-qbitvpn",
    "docker-uptime_kuma",
    "docker",
    "filebrowser",
    "home-assistant",
    "jellyfin",
]
