title: "Richie Cahill"
description: "ALL THE CHAOS THAT I CANT DO AT WORK"
baseurl: "" # empty for user site, or "/my-blog" for project site
url: "https://richiecahill.github.io"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5
paginate_path: "/page:num"

author:
  name: "Richie Cahill"
  email: "richie@tmmworkshop.com"

social_links:
  github: "RichieCahill"
  website: "https://tmmworkshop.com"
