name: build_jeeves
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: build_jeeves
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Build default package
        run: 'nix-shell -p nixos-rebuild --run "nixos-rebuild build --flake ./#jeeves"'
