name: Daily Pull Request

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Make changes
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/kernel_packages_update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Base linuxPackages update
          title: Base linuxPackages update
          body: |
            Update linuxPackages
          branch: daily-update
          delete-branch: true
