name: Auto Merge Pull Request
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Enable auto-merge
        run: gh pr merge flake_lock_update --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
