name: treefmt
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  treefmt:
    name: nix fmt
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: runs treefmt
        run: "treefmt --ci"
