name: treefmt

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  treefmt:
    name: nix fmt
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: get_version
        run: treefmt --version
      - name: runs treefmt
        run: treefmt --ci $( [ -n "$ACTIONS_RUNNER_DEBUG" ] && echo -vv )