name: build_systems
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: nix fmt
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build default package
        run: "treefmt --ci"
